# nixpacks.toml

[phases.setup]
# We don't need a specific setup phase here, but it's good to know it exists.

[phases.install]
# The install command should be run from the 'backend' directory
path = "backend/"
cmds = ["npm install"]

[phases.build]
# The build command should be run from the 'backend' directory
path = "backend/"
cmds = [] # No build command is necessary for this project

[start]
# The start command should be run from the 'backend' directory
path = "backend/"
cmd = "npm start"